# User Test
#------------------------------------

APP              = test
APP_SRCS        += ./SRC/test_cluster_frequency.c
APP_INC	        += ./INC/.
APP_CFLAGS      +=

include $(RULES_DIR)/pmsis_rules.mk
