# User Test
#------------------------------------

APP              = test
APP_SRCS        += ./SRC/perf.c ./SRC/usr_fft.c
APP_INC	        += ./INC/.
APP_CFLAGS      +=

include $(RULES_DIR)/pmsis_rules.mk
