# User Test
#------------------------------------

APP              = usart
APP_SRCS        += ./SRC/usart_demo.c ./SRC/usr_usart.c
APP_INC	        += ./INC/.
APP_CFLAGS      +=

PLPBRIDGE_FLAGS += -f ./SRC/usart_demo.c ./SRC/usr_usart.c -hyper

include $(RULES_DIR)/pmsis_rules.mk