# User Test
#------------------------------------

APP              = test
APP_SRCS        += ./SRC/helloworld.c
APP_INC         += ./INC/.
APP_CFLAGS      += 



PMSIS_OS = pulpos


include $(RULES_DIR)/pmsis_rules.mk
